<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityManager;
use Voiceworks\HexagonalApp\Domain\UserManagement\User\User;
use AppBundle\Entity\User as DoctrineUser;
use Voiceworks\HexagonalApp\Domain\UserManagement\User\UserRepository as BaseUserRepository;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository implements BaseUserRepository
{

    private $em;

    public function __construct(EntityManager $entityManager)
    {
        $this->em = $entityManager;
    }
    /**
     * {@inheritdoc}
     */
    public function findById(int $id): User
    {
        return $this->em->find(DoctrineUser::class, $id);
    }

    /**
     * {@inheritdoc}
     */
    public function findByEmail(string $email): User
    {
       return $this->em->find(DoctrineUser::class, $email);
    }

    /**
     * {@inheritdoc}
     */
    public function save(User $user) : User
    {
        $doctrineUser = new DoctrineUser($user);
        $this->em->persist($doctrineUser);
        $this->em->flush();
        return $doctrineUser;
    }
    /**
     * @param int $limit
     * @param int $offset
     *
     * @return User[]
     */
    public function findAll(int $limit, int $offset): array
    {
        // TODO: Implement findAll() method.
    }
}
